### ISSUE TITLE
Automate check using GitHub action

### ISSUE THREAD

**Issue by nobuyuki83** [goto-c/OpenGL#8]
Try using GitHub action to automatically build the project when pushed. 

This saves a lot of time to check and verify the project. 

It's extremely easy. You just put a YAML file at ```.github/workflows/```

Read this article and try it out:
https://qiita.com/HeRo/items/935d5e268208d411ab5a

**Comment by nobuyuki83** [comment]
You can check the status here: 
https://github.com/goto-c/OpenGL/actions

Currently, it fails to build the code. Put the build commands like following in the YAML file:

```
git clone https://github.com/goto-c/OpenGL.git
git submodule update --init --recursive,
cd 3rd_party/glfw
cmake .
make
cd ../../
mkdir build
cd build
cmake .
make
```

**Comment by goto-c** [comment]
![スクリーンショット 2020-07-08 20 30 23](https://user-images.githubusercontent.com/61488975/86913770-10206f80-c15a-11ea-83c7-e959b777df7e.png)

First cmake seems to have failed unfortunately. What's wrong ?

**Comment by nobuyuki83** [comment]
If there are error messages, try to read it by yourself. If you cannot understand the English sentence, use Google translate. 

![Screenshot 2020-07-08 21 01 27](https://user-images.githubusercontent.com/40525402/86917473-13b6f500-c160-11ea-9922-1f2157299c75.png)
This means that there is no OpenGL installed. Use ```apt-get``` commands to install OpenGL environment on Ubuntu. 

https://qiita.com/BitPositive/items/db8b13e7d34e5349237b

**Comment by goto-c** [comment]
I see.. I will try, thank you.

**Comment by goto-c** [comment]
I think I wrote workflow files for the latest version of mac, windows, and ubuntu .
I also edited CMakeLists.txt of all projects to support build in windows and Linux.


![スクリーンショット 2020-07-09 16 33 54](https://user-images.githubusercontent.com/61488975/87011462-e7a08000-c202-11ea-843d-bdbb437a081d.png)

But I didn't use ```make``` command in the workflows at all, because when I wrote it, the error message said makefile didn't exist. I couldn't find makefile in the ```ls``` list as well.
Does ```cmake``` command do all processes in this case ?

**Comment by nobuyuki83** [comment]
The YAML files Look almost there. Great you made the code compilable for Windows, Ubuntu, and Mac. 

The script is very fragmented and should be merged. Please also notice that each ```run``` starts from the top directory path ```OpenGL/```.

For example, this script 

```yaml
    - name: cd->glfw
      run: cd 3rd_party/glfw
    - name: cmake
      run: cmake . --help-policy CMP0072
```

should be written as

```yaml
    - name: compile glfw
      run: | 
        cd 3rd_party/glfw
        cmake . --help-policy CMP0072
        make
```

> Does cmake command do all processes in this case ?

cmake has a build command ```cmake --bluid . ```

The following code 

```yaml
    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: check
      run: |
        pwd
        ls
    - name: cmake
      run: |
        cd build
        cmake -G Xcode ..
```

can be written as

```yaml
    - name: build examples
      run: |
        mkdir build
        cd build
        cmake -G Xcode ..
        cmake --build .
```
